![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np
my_array = np.arange(10)
print("1. Crea un array que vaya del 0 al 9 y que se llame `my_array`:\n", my_array, "\n")

#son los elementos impares ordenados descendentemente
nuevo_array = my_array[my_array % 2 != 0][::-1]
print("2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden:\n",nuevo_array)



1. Crea un array que vaya del 0 al 9 y que se llame `my_array`:
 [0 1 2 3 4 5 6 7 8 9] 

2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden:
 [9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
#por posicion
print("Imprime por pantalla la secuencia [8 7] del array `my_array`\n",my_array[7:9][::-1],"\n")

#filtrado
print("Imprime por pantalla la secuencia [8 7] del array `my_array`\n",my_array[(my_array>6) & (my_array<9)][::-1])

Imprime por pantalla la secuencia [8 7] del array `my_array`
 [8 7] 

Imprime por pantalla la secuencia [8 7] del array `my_array`
 [8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
#por posicion
print("Imprime por pantalla la secuencia [2 1 0] de `my_array`\n",my_array[:3][::-1])

#filtrado
print("Imprime por pantalla la secuencia [2 1 0] de `my_array`\n",my_array[(my_array<3)][::-1])

Imprime por pantalla la secuencia [2 1 0] de `my_array`
 [2 1 0]
Imprime por pantalla la secuencia [2 1 0] de `my_array`
 [2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
my_array = np.arange(1,21).reshape(4,5)
print("1. Crea una matriz de 4x5, con una secuencia del 1 al 20:\n",my_array,"\n")
print("2. Invierte totalmente la matriz. Tanto las filas, como las columnas:\n",my_array.transpose())

1. Crea una matriz de 4x5, con una secuencia del 1 al 20:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

2. Invierte totalmente la matriz. Tanto las filas, como las columnas:
 [[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [6]:

my_array[0:2, 0:2].copy()

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [7]:

my_array[0::2, 0::2].copy()

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [8]:
my_array[0:3, ::-1].copy()

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [9]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[x=="Loro"])

['Loro' 'Loro']


In [10]:
print(np.extract(x=="Loro",x))

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [11]:
matriz = np.arange(20).reshape(2,5,2)
print(matriz)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [12]:
zeros = np.zeros(10, dtype=np.int8)
print('Tamaño en memoria',zeros.nbytes,"\n")
zeros[3]=1
print("Array:",zeros,"\n")
print('Tamaño en memoria',zeros.nbytes,"\n")

Tamaño en memoria 10 

Array: [0 0 0 1 0 0 0 0 0 0] 

Tamaño en memoria 10 



## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [13]:
#usando solo numpy
vector = np.arange(10,50)
print("Crea un vector que vaya del 10 al 49\n", vector, "\n")
print("Inviértelo:\n", vector[::-1])

Crea un vector que vaya del 10 al 49
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Inviértelo:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
#usando pandas y numpy
import pandas as pd
vector = pd.Series(np.arange(10,50))
print("Crea un vector que vaya del 10 al 49\n", vector.values, "\n")
print("Inviértelo:\n",vector.sort_values(ascending=False).values)

Crea un vector que vaya del 10 al 49
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Inviértelo:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [15]:
# Utilizando el nonzero del tipo ndarray.
# Devuelve una tupla con la lista de los indices cuyos valores no sean 0. El número de elementos de la tupla es la dimesión de la matriz
# Como es un vector, tiene una dimensión y, la tupla solo tendrá un elemento de tipo array con las posiciones cuyo valor es distinto de cero.
def return_vector_non_zero_values(*vector:dict[np.ndarray])->np.ndarray:
    """ 
    Dado un vector, función que devuelve los indices de los valores distintos a 0
    
    Input:
        vector: ndarray
    """
    return np.array(vector).nonzero()[0]


print(return_vector_non_zero_values(1,2,0,0,4,0))

[0 1 4]


In [16]:
#utilizando el flatnonzero de la libreria numpy. Devuelve todos los valores en un vector, sin separarlos por dimensión
def return_vector_non_zero_values(*vector:tuple[np.array])->np.array:
    """ 
    Dado un vector, función que devuelve los indices de los valores distintos a 0
    
    Input:
        vector: ndarray
    """
    return np.flatnonzero(np.array(vector))



# print(return_vector_non_zero_values(1,2,0,0,4,0))
vector = np.array([[1,2,3,4], [0,0,0,0]])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [17]:
np.random.seed(35454)
matriz_aletaria = np.random.randint(200, size=(10,10))
print("Matriz_aletaria:\n", matriz_aletaria)
matriz_aletaria.min()
print("Minimo",matriz_aletaria.min())
print("Máximo",matriz_aletaria.max())

Matriz_aletaria:
 [[ 58  80 169  44  95 115 125  78 145 112]
 [139 100 106 138  11  82 104 196  21 128]
 [100 152   4  80 129 117  46 125  22  30]
 [130  84 147 105 140 113  33 152 176 106]
 [ 49   5  31 169  14   2 117  38 124  96]
 [ 52  34   6 151 101   4  15  99 188 190]
 [ 44   6 108  74  51 193 158 164 144  19]
 [ 75 181   0  72 139  36  64  48 163 138]
 [145 192  11  92 185 101 121  10 191  21]
 [ 54  16 138 170  97 167  52 155  98 145]]
Minimo 0
Máximo 196


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [18]:
np.random.seed(35454)
vector_aletario = np.random.randint(10000, size=(30))
print("Vector_aletario:\n", vector_aletario)

#media usando metodo de ndarray
print("Media",vector_aletario.mean())

#media calculando pero usando metodos de ndarray para obtener valores
print("Media",vector_aletario.sum()/vector_aletario.size)

#media usando funciones de python
print("Media",sum(vector_aletario)/len(vector_aletario))


Vector_aletario:
 [ 570 2729 5235 9947  125 6801 1904 4491 1515 7018 6026 3339 1106 5736
 1988 5141  152 8272 6525 1814 8834 1620 7564 3557 1137 8993 1518 6552
  467 5082]
Media 4191.933333333333
Media 4191.933333333333
Media 4191.933333333333


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [19]:

orden = 6

#creo una array cuadrado con todos los valores a 0 
matriz = np.zeros(shape=(orden,orden), dtype=np.int8)   
matriz[0]=1 #pongo a 1 la fila 0
matriz[matriz.shape[0]-1]=1 #pongo a 1 la última fila
matriz[:,0]=1 #pongo a 1 la columna 0
matriz[:, matriz.shape[0]-1]=1 #pongo a 1 la última columna
print(matriz, "\n")

matriz = pd.DataFrame(np.zeros(shape=(orden,orden), dtype=np.int8))
matriz[matriz.columns.start]=1 #pongo a 1 la primera columna
matriz[matriz.columns.stop-1]=1  #pongo a 1 la última columna
matriz.loc[matriz.index.start]=1 #pongo a 1 la primera fila
matriz.loc[matriz.index.stop-1]=1 #pongo a 1 la última fila
print(matriz.values)



[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]] 

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [26]:

def matriz_cuadrada_alterna(orden:int)->np.ndarray:
    """ 
    Dado un orden, devuelve una matriz cuadrada con los valores alternos 0-1
    Ejemplo de resultado con orden=4
    [
        [0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]
    ]
    
    Inputs:
        orden: int orden de la matriz cuadrada
        
    Outputs:
        matriz: ndarray
    """
    # Voy a sacar el 1 ó 0 a partir del modulo dividiendo la posición entre 2 (par vs impar)
    # Daré un valor a cada celda que será la posicion secuencial en la matriz orden x orden
    # Es una secuencia del 0 al orden^2-1, que será la posicion secuencial para todos los elementos
    secuencia_inicial = np.arange(orden**2).reshape(orden,orden)
    print(f"Posiciones secuenciales en la matriz {orden}x{orden}\n", secuencia_inicial, "\n")

    # En función del número de columnas, el inicio de las filas impares tiene que ser un valor par o impar.
    # Voy a crear una matriz de 2 dimensiones 1 x orden que tendrá los valores 0 o 1.
    # En las filas pares tenrá el valor 0 y en los impares 1 si el orden es par y 0 si el orden es impar
    # así, cuando el orden es par sumamos un 1 a los elementos del vector de las filas impares.
    vector_suma_impares = np.zeros(orden, dtype=np.int8) # vector de "orden" con valores a 0
    vector_suma_impares[1::2] = (orden+1) % 2 # modicamos los valores en las posiciones impares para que valga 1 si el orden es par.
    matriz_suma_impares = vector_suma_impares.reshape(-1,1) # creamos una matriz de 1 x orden a partur del vector anterior
    
    print(F"Matriz 1x{orden}\n", matriz_suma_impares, "\n")
    
    
    # Sumo la nueva matriz a la matriz secuencia_inicial y así se modificarán los elementos por fila,
    # sumando el único valor de la fila de la matriz matriz_orden a cada uno de los elementos de la fila de la matriz secuencia_inicial
    matriz_secuencia_alterna = secuencia_inicial + matriz_suma_impares

    # ahora ya tengo una matriz donde hay "orden" filas y "orden" columnas
    # donde los valores de las columnas en cada fila son consecutivos (al dividir entre 2 el modulo me dará 1 ó 0)
    # y el número inicial de la columna por cada fila es par/impar consecutivamente.    
    print(F"Resultado suma de las matrices\n", matriz_secuencia_alterna, "\n")
    
    # saco el modulo de la division entre 2 para toda la matriz
    return matriz_secuencia_alterna % 2



print("Matriz cuadrada alterna:\n", matriz_cuadrada_alterna(8))



Posiciones secuenciales en la matriz 8x8
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]] 

Matriz 1x8
 [[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]] 

Resultado suma de las matrices
 [[ 0  1  2  3  4  5  6  7]
 [ 9 10 11 12 13 14 15 16]
 [16 17 18 19 20 21 22 23]
 [25 26 27 28 29 30 31 32]
 [32 33 34 35 36 37 38 39]
 [41 42 43 44 45 46 47 48]
 [48 49 50 51 52 53 54 55]
 [57 58 59 60 61 62 63 64]] 

Matriz cuadrada alterna:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [52]:
a = np.array([[0,1], [1,0]])
print(np.tile(a, (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [22]:
np.random.seed(31312)
matriz = np.random.randint(20, size=(5,5))
print("Matriz con valores aleatorios:\n",matriz,"\n")
media = np.mean(matriz)
print("Media",media,"\n")
desviacion = np.std(matriz)
print("Desviación",desviacion,"\n")
print("Matriz normalizada:\n", (matriz-media)/desviacion)


Matriz con valores aleatorios:
 [[ 9  3  5  5  0]
 [ 7 14 17  7 13]
 [14 12  4  0  9]
 [ 3  0 17  0  6]
 [ 8  8  9 18  7]] 

Media 7.8 

Desviación 5.381449618829484 

Matriz normalizada:
 [[ 0.22298824 -0.89195298 -0.5203059  -0.5203059  -1.44942359]
 [-0.14865883  1.15210593  1.70957654 -0.14865883  0.96628239]
 [ 1.15210593  0.78045885 -0.70612944 -1.44942359  0.22298824]
 [-0.89195298 -1.44942359  1.70957654 -1.44942359 -0.33448237]
 [ 0.03716471  0.03716471  0.22298824  1.89540007 -0.14865883]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [23]:
#1
vector = np.arange(11)
print("1.Secuencia:\n", vector,"\n")

#creo el patrón con la concicion que voy a aplicar al filtrar: valores entre el 3 y el 8
#la he creado en una variable porque se va a utilizar más de una vez, sino, se podría poner directamente en la sentencia de filtrado.
patron_filtrado = (vector > 2) & (vector < 9)


#2
nuevo_vector= np.where(patron_filtrado, -1, vector).copy()
print("2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.\n", nuevo_vector,"\n")

#3
#supongo que obtener la negación es el valor que al sumar con valor de la matriz inicial tiene que dar 0
#voy a multiplicar por -1 los valores que hemos filtrado.
#el resto de valores del vector los pondré a cero para que no modifiquen al sumar
np.invert(vector).copy()
vector_negado = np.where(patron_filtrado, vector*-1, np.zeros(11, dtype=np.int8)).copy()
print("3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8:\n", vector_negado, "\n")

print("Compruebo que la suma del vector y el vector inverso tiene valor 0 en los elementos filtrados. El resto de valores del vector los dejo igual:\n", vector + vector_negado , "\n")


1.Secuencia:
 [ 0  1  2  3  4  5  6  7  8  9 10] 

2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
 [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10] 

3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8:
 [ 0  0  0 -3 -4 -5 -6 -7 -8  0  0] 

Compruebo que la suma del vector y el vector inverso tiene valor 0 en los elementos filtrados. El resto de valores del vector los dejo igual:
 [ 0  1  2  0  0  0  0  0  0  9 10] 

